binary-path = "./input/light-firmware-debug"
report-path = "./report.md"

[binary]
args = ["--hostname", "arco", "--domain", "arco"]

[valgrind]
args = ["--leak-check=full", "--track-origins=yes", "--error-exitcode=1"]
