# Binary path.
#
# It must be an existing file path. Every other path type will be rejected.
binary-path = "./input/light-firmware-debug"
# Report path.
#
# It can be a file or a directory path. In the second case, the `lich.ext` file
# will be created.
report-path = "./report.md"

# All options for the binary to be evaluated.
[binary]
# Binary input arguments.
args = ["--hostname", "arco", "--domain", "arco"]

# Optional valgrind options.
[valgrind]
enabled = false
args = ["--leak-check=full", "--track-origins=yes", "--error-exitcode=1"]
# A timeout for running the binary. If the value is 0, the timeout is disabled.
# The base measurement unit is second.
timeout = 10

# Optional powerstat options.
[powerstat]
enabled = false
# Take a sample each second and run for 60 seconds (1 minute). Use Intel RAPL
# to extract energy consumption data and forcibly ignore zero power rate stats
# from the battery. The 60s is the minimum allowed duration.
args = ["-zR", "1", "60", "--"]

# Optional powertop options.
[powertop]
enabled = false
args = ["--time=10", "--csv=output.csv"]
