# Binary path.
#
# It must be an existing file path. Every other path type will be rejected.
binary-path = "./input/light-firmware-debug"
# Report path.
#
# It must be a directory path. The final report and every tool report will be
# saved in this directory.
report-path = "./lich"
# Set the root for the system in use.
root = "sudo"

# All input arguments for the binary in analysis.
[binary]
# Binary input arguments.
args = ["--hostname", "arco", "--domain", "arco"]

# Optional valgrind arguments.
[valgrind]
# Run valgrind tool.
enable = true
# Valgrind input arguments.
args = ["--leak-check=full", "--track-origins=yes", "--error-exitcode=1"]
# A timeout to stop binary execution. This parameter is useful when a server is
# being tested.. When the value is 0, the timeout is disabled.
# The basic measurement unit for this option is second [s].
timeout = 10

# Optional powerstat arguments.
[powerstat]
# Do not run powerstat tool.
enable = true
# Powerstat input arguments.
#
# Take a sample each second and run for 60 seconds (1 minute). Use Intel RAPL
# to extract energy consumption data and forcibly ignore zero power rate stats
# from the battery. The 60s is the minimum allowed duration.
args = ["-zR", "1", "60", "--"]

# Optional powertop arguments.
[powertop]
# Run powertop tool.
enable = true
# Powertop input arguments.
args = ["--time=10", "--csv=output.csv"]
