# Binary path.
#
# It must be an existing file path. Every other path type will be rejected.
binary-path = "light-firmware"
# Report path.
#
# It must be a directory path. The final report and every tool report will be
# saved in this directory.
report-path = "lich"
# Enable docker configuration.
docker = true

# All input arguments for the binary in analysis.
[binary]
# Binary input arguments.
args = ["--hostname", "arco", "--domain", "arco"]

# Optional valgrind arguments.
[valgrind]
# Run valgrind tool. If `false`, the tool does not run.
enable = true
# Valgrind input arguments.
args = ["--leak-check=full", "--show-leak-kinds=all", "--track-origins=yes", "--error-exitcode=1"]
# A timeout to stop binary execution. This parameter is useful when a server is
# being tested.. When the value is 0, the timeout is disabled.
# The basic measurement unit for this option is second [s].
timeout = 10

# Optional perf arguments.
[perf]
# Run perf tool. If `false`, the tool does not run.
enable = true
# Perf input arguments.
#
# Run for 10s (basic measurement unit is milliseconds).
args = ["stat", "--timeout", "10000", "-ae", "power/energy-cores/,power/energy-pkg/,power/energy-psys/"]

# Optional powerstat arguments.
[powerstat]
# Run powerstat tool. If `false`, the tool does not run.
# FIXME: Disable powerstat because it does not work on `debian bookworm`
enable = false
# Powerstat input arguments.
#
# Take a sample each second and run for 60 seconds (1 minute). Use Intel RAPL
# to extract energy consumption data and forcibly ignore zero power rate stats
# from the battery. The 60s is the minimum allowed duration.
args = ["-zR", "1", "60", "--"]

# Optional powertop arguments.
[powertop]
# Run powertop tool. If `false`, the tool does not run.
enable = true
# Powertop input arguments.
args = ["--time=10"]
# Csv output path.
csv-output = "output.csv"
