name: lich-docker-images

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  docker-images:

    strategy:
      matrix:
        arch:
         - amd64
         - arm64
        image:
         - alpine
         - linux
        include:
         - arch: amd64
           runner: ubuntu-latest
           image: alpine
         - arch: amd64
           runner: ubuntu-latest
           image: linux
         - arch: arm64
           runner: ubuntu-24.04-arm
           image: alpine
         - arch: arm64
           runner: ubuntu-24.04-arm
           image: linux

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub container registry (ghcr.io)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile-${{ matrix.image }}
        platforms: linux/${{ matrix.arch }}
        load: true
        tags: |
          ghcr.io/softengpolito/lich-${{ matrix.image }}-${{ matrix.arch }}:test

    - name: Test
      run: |
        docker run --rm --privileged \
               -v ./input/${{ matrix.image }}:/lich \
               ghcr.io/softengpolito/lich-${{ matrix.image }}-${{ matrix.arch }}:test

    - name: Print valgrind output
      run: |
        cat input/${{ matrix.image }}/lich/valgrind.md

    - name: Print perf output
      run: |
        cat input/${{ matrix.image }}/lich/perf.md

    - name: Print powerstat output
      if: matrix.image == 'alpine'
      run: |
        cat input/${{ matrix.image }}/lich/powerstat.md

    - name: Print powertop output
      run: |
        cat input/${{ matrix.image }}/lich/powertop.md

    - name: Get tag
      if: startsWith(github.ref, 'refs/tags/v')
      id: tag
      run: |
        ONLY_VERSION=$(echo $GITHUB_REF | sed -E 's/refs\/tags\/v//')
        echo "value=$ONLY_VERSION" >> $GITHUB_OUTPUT

    - name: Build and push
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Dockerfile-${{ matrix.image }}
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ghcr.io/softengpolito/lich-${{ matrix.image }}-${{ matrix.arch }}:latest
          ghcr.io/softengpolito/lich-${{ matrix.image }}-${{ matrix.arch }}:${{ steps.tag.outputs.value }}


