name: perf

on:
  push:
    branches:
      - perf

jobs:
  perf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install perf
      run: |
        sudo apt-get update && sudo apt-get install linux-tools-common \

    - name: Enable perf event paranoid flag
      run: sudo sysctl kernel.perf_event_paranoid=1

    - name: Set Kernel KPTR  Restriction
      run: sudo sysctl kernel.kptr_restrict=0

    - name: Cpu Info
      run: cat /proc/cpuinfo

    - name: Perf info
      run: cat /boot/config-$(uname -r) | grep PERF_EVENTS

    - name: Perf list
      run: sudo perf list

    - name: Run perf
      run: sudo perf stat --timeout 10000 -ae power/energy-cores/,power/energy-pkg/,power/energy-psys/
